### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by al8n** [al8n/memberlist#5]
# Stage 1

- [x] Transports support
  - [x] TCP/TLS/NativeTLS & UDP Transport
     - [x] TCP #10 
     - [x] TLS #11 
     - [x] ~~NativeTLS #12~~ `native-tls` supports was removed in #71
  - [x] QUIC & QUIC Transport #15 
     - [x] `quinn` support #15 
     - [x] ~~`s2n` support #15~~ `s2n` supports was removed in #71 
- [x] Testing
  - [x] state unit tests #25 
  - [x] network unit tests
      - [x] `NetTransport` unit tests #14 
      - [x] `QuicTransport` unit tests #16
  - [x] memberlist unit tests #25 
  - [x] Add CI
      - [x] Code coverage over `75%`
- [x] Documentation
  - [x] `100%` document

# Stage 2
- [ ] QUIC & UDP Transport support
- [ ] Tutorials

# Version 1.0.0
- [ ] Reimplement gossip protocol in Sans-I/O architecture.

# Long-term Goal
- [ ] Bindings to `Python`
- [ ] Bindings to  `NodeJS`
- [ ] Bindings to `Zig`
